### ISSUE TITLE
pip install pyhash on "CentOS release 6.4 (Final)" fails

### ISSUE THREAD

**Issue by johnrfrank** [flier/pyfasthash#1]
pip install pyhash on "CentOS release 6.4 (Final)" fails

Downloading/unpacking pyhash
  Running setup.py egg_info for package pyhash
    warning: no files found matching '_.cc' under directory 'src'
Installing collected packages: pyhash
  Running setup.py install for pyhash
    building '_pyhash' extension
    gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DBOOST_PYTHON_STATIC_LIB -I/usr/include/python2.6 -c src/Hash.cpp -o build/temp.linux-x86_64-2.6/src/Hash.o -msse4.2
    In file included from src/Hash.cpp:1:
    src/Hash.h:20: error: ‘__int128’ does not name a type
    In file included from src/Hash.cpp:1:
    src/Hash.h:74: error: ISO C++ forbids declaration of ‘uint128_t’ with no type
    src/Hash.h:74: error: expected ‘,’ or ‘...’ before ‘&’ token
    src/Hash.h:74: error: template-id ‘convert<>’ for ‘PyObject_ internal::convert(int)’ does not match any template declaration
    src/Hash.h:148: error: expected constructor, destructor, or type conversion before ‘extract_hash_value’
    In file included from src/Hash.cpp:4:
    src/MurmurHash.h:49: error: ‘uint128_t’ was not declared in this scope
    src/MurmurHash.h:49: error: template argument 1 is invalid
    src/MurmurHash.h:49: error: invalid type in declaration before ‘;’ token
    src/MurmurHash.h:50: error: ‘uint128_t’ was not declared in this scope
    src/MurmurHash.h:50: error: template argument 1 is invalid
    src/MurmurHash.h:50: error: invalid type in declaration before ‘;’ token
    In file included from src/Hash.cpp:4:
    src/MurmurHash.h:111: error: expected initializer before ‘murmur_t’
    src/MurmurHash.h:121: error: expected initializer before ‘murmur_t’
    In file included from src/Hash.cpp:7:
    src/CityHash.h:37: error: ‘uint128_t’ was not declared in this scope
    src/CityHash.h:37: error: template argument 1 is invalid
    src/CityHash.h:37: error: invalid type in declaration before ‘;’ token
    src/CityHash.h:50: error: expected initializer before ‘city_hash_t’
    src/CityHash.h: In static member function ‘static void Hasher<T>::Export(const char*) [with T = int]’:
    src/CityHash.h:111: error: invalid use of qualified-name ‘::has_sse4_2’
    src/CityHash.h:114: error: ‘city_hash_128_t’ is not a class or namespace
    src/CityHash.h:115: error: ‘city_hash_128_t’ is not a class or namespace
    In file included from src/Hash.cpp:8:
    src/SpookyHash.h: At global scope:
    src/SpookyHash.h:28: error: ‘uint128_t’ was not declared in this scope
    src/SpookyHash.h:28: error: template argument 1 is invalid
    src/SpookyHash.h:28: error: invalid type in declaration before ‘;’ token
    src/SpookyHash.h:43: error: expected initializer before ‘spooky_hash_t’
    src/Hash.cpp: In function ‘void init_module__pyhash()’:
    src/Hash.cpp:26: error: invalid use of qualified-name ‘::Export’
    src/Hash.cpp:27: error: invalid use of qualified-name ‘::Export’
    src/Hash.cpp:35: error: invalid use of qualified-name ‘::Export’
    src/Hash.cpp:39: error: invalid use of qualified-name ‘::Export’
    error: command 'gcc' failed with exit status 1
    Complete output from command /home/ec2-user/ve-test/bin/python -c "import setuptools;**file**='/home/ec2-user/ve-test/build/pyhash/setup.py';exec(compile(open(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /var/tmp/pip-pQnECp-record/install-record.txt --single-version-externally-managed --install-headers /home/ec2-user/ve-test/include/site/python2.6:
    running install

running build

running build_py

creating build

creating build/lib.linux-x86_64-2.6

copying pyhash.py -> build/lib.linux-x86_64-2.6

running build_ext

building '_pyhash' extension

creating build/temp.linux-x86_64-2.6

creating build/temp.linux-x86_64-2.6/src

creating build/temp.linux-x86_64-2.6/src/fnv

creating build/temp.linux-x86_64-2.6/src/lookup3

creating build/temp.linux-x86_64-2.6/src/SuperFastHash

creating build/temp.linux-x86_64-2.6/src/smhasher

gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DBOOST_PYTHON_STATIC_LIB -I/usr/include/python2.6 -c src/Hash.cpp -o build/temp.linux-x86_64-2.6/src/Hash.o -msse4.2

In file included from src/Hash.cpp:1:

src/Hash.h:20: error: ‘__int128’ does not name a type

In file included from src/Hash.cpp:1:

src/Hash.h:74: error: ISO C++ forbids declaration of ‘uint128_t’ with no type

src/Hash.h:74: error: expected ‘,’ or ‘...’ before ‘&’ token

src/Hash.h:74: error: template-id ‘convert<>’ for ‘PyObject\* internal::convert(int)’ does not match any template declaration

src/Hash.h:148: error: expected constructor, destructor, or type conversion before ‘extract_hash_value’

In file included from src/Hash.cpp:4:

src/MurmurHash.h:49: error: ‘uint128_t’ was not declared in this scope

src/MurmurHash.h:49: error: template argument 1 is invalid

src/MurmurHash.h:49: error: invalid type in declaration before ‘;’ token

src/MurmurHash.h:50: error: ‘uint128_t’ was not declared in this scope

src/MurmurHash.h:50: error: template argument 1 is invalid

src/MurmurHash.h:50: error: invalid type in declaration before ‘;’ token

In file included from src/Hash.cpp:4:

src/MurmurHash.h:111: error: expected initializer before ‘murmur_t’

src/MurmurHash.h:121: error: expected initializer before ‘murmur_t’

In file included from src/Hash.cpp:7:

src/CityHash.h:37: error: ‘uint128_t’ was not declared in this scope

src/CityHash.h:37: error: template argument 1 is invalid

src/CityHash.h:37: error: invalid type in declaration before ‘;’ token

src/CityHash.h:50: error: expected initializer before ‘city_hash_t’

src/CityHash.h: In static member function ‘static void Hasher<T>::Export(const char*) [with T = int]’:

src/CityHash.h:111: error: invalid use of qualified-name ‘::has_sse4_2’

src/CityHash.h:114: error: ‘city_hash_128_t’ is not a class or namespace

src/CityHash.h:115: error: ‘city_hash_128_t’ is not a class or namespace

In file included from src/Hash.cpp:8:

src/SpookyHash.h: At global scope:

src/SpookyHash.h:28: error: ‘uint128_t’ was not declared in this scope

src/SpookyHash.h:28: error: template argument 1 is invalid

src/SpookyHash.h:28: error: invalid type in declaration before ‘;’ token

src/SpookyHash.h:43: error: expected initializer before ‘spooky_hash_t’

src/Hash.cpp: In function ‘void init_module__pyhash()’:

src/Hash.cpp:26: error: invalid use of qualified-name ‘::Export’

src/Hash.cpp:27: error: invalid use of qualified-name ‘::Export’

src/Hash.cpp:35: error: invalid use of qualified-name ‘::Export’

src/Hash.cpp:39: error: invalid use of qualified-name ‘::Export’

error: command 'gcc' failed with exit status 1
---

Cleaning up...
Command /home/ec2-user/ve-test/bin/python -c "import setuptools;**file**='/home/ec2-user/ve-test/build/pyhash/setup.py';exec(compile(open(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /var/tmp/pip-pQnECp-record/install-record.txt --single-version-externally-managed --install-headers /home/ec2-user/ve-test/include/site/python2.6 failed with error code 1 in /home/ec2-user/ve-test/build/pyhash
Traceback (most recent call last):
  File "/home/ec2-user/ve-test/bin/pip", line 9, in <module>
    load_entry_point('pip==1.4', 'console_scripts', 'pip')()
  File "/home/ec2-user/ve-test/lib/python2.6/site-packages/pip/**init**.py", line 148, in main
    return command.main(args[1:], options)
  File "/home/ec2-user/ve-test/lib/python2.6/site-packages/pip/basecommand.py", line 169, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 26: ordinal not in range(128)

**Comment by flier** [comment]
since there are [a lot of situation](https://svn.boost.org/trac/boost/ticket/8048), I prefer to use `typedef boost::uint128_type uint128_t`
