### ISSUE TITLE
Is it possible to do a PyPI release of 0.7?

### ISSUE THREAD

**Issue by shanx** [flier/pyfasthash#11]
Thanks a lot for your work on pyhash! I would like to use city_crc_128 in a production setting and would much rather version pin against a pypi version then introduce an editable :) Would it be possible for you to do an actual deploy of pyhash to PyPI? 

Thanks a lot!

**Comment by flier** [comment]
I have upload a new release v0.8 to [PyPi](https://pypi.python.org/pypi/pyhash), but it must be build and use with `boost-python` library
