### ISSUE TITLE
pip install pyhash needs setuptools>=5.4.1 but does not list as a requirement

### ISSUE THREAD

**Issue by johnrfrank** [flier/pyfasthash#2]
This package depends on a very new version of setuptools, but does not list it as an install_requirement in its call to setup in setup.py

Consider adding the following just above this line https://github.com/flier/pyfasthash/blob/master/setup.py#L111

```
install_requires=[
    'setuptools >= 5.4.1',
],
```

**Comment by flier** [comment]
added, thanks
