### ISSUE TITLE
[question] Differrent values on other implementations (murmur3 32 bits)

### ISSUE THREAD

**Issue by thor27** [flier/pyfasthash#24]
Hi!

I'm seeing different values when using other murmur libs in python, take a look:
```python
In [1]: import pyhash

In [2]: import mmh3 # https://github.com/hajimes/mmh3

In [3]: import pymmh3 # https://github.com/wc-duck/pymmh3

In [4]: pyhash.murmur3_32()('foo')
Out[4]: 2085578581

In [5]: mmh3.hash('foo', signed=False)
Out[5]: 4138058784

In [10]: pymmh3.hash('foo') + 2**32
Out[10]: 4138058784
```
I've also tried this online tool: http://murmurhash.shorelabs.com/ with the same **4138058784**
 hash value. Why the values from pyhash differs from other implementations? it's possible to get the same result?

Thanks!

**Comment by flier** [comment]
It seems you use Python 3.0? 

I have reproduced the issue in Python 2.7, the unicode string will be hashed to 4138058784.

```python
In [1]: import pyhash

In [2]: pyhash.murmur3_32()('foo')
Out[2]: 4138058784L

In [3]: pyhash.murmur3_32()(u'foo')
Out[3]: 2085578581L
```

**Comment by flier** [comment]
please try the latest git commit, it should be aligned in both Python 2.x and 3.x

**Comment by thor27** [comment]
Yes, I was using python3, I will update here and test. Thanks.

**Comment by thor27** [comment]
Hi, the syntax of numbers with L at the end does not work on python3:

```python
In [1]: import pyhash
Traceback (most recent call last):

  File "/home/thomaz/projetos/thumbor/vpython-pyfasthash/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-1-6937f29f5d7b>", line 1, in <module>
    import pyhash

  File "/home/thomaz/projetos/thumbor/pyfasthash/pyhash.py", line 89
    bytes_hash=3698262380L,
                         ^
SyntaxError: invalid syntax
```

**Comment by thor27** [comment]
I've tryed to just remove all "L" and seems to import fine, but doesn't works:
```python
In [1]: import pyhash

In [2]: pyhash.murmur3_32()('foo'.encode('ascii'))
Out[2]: 4138058784

In [3]: pyhash.murmur3_32()('foo')
Out[3]: 2085578581
```

**Comment by thor27** [comment]
Hi!
That is ok, I understood, but having different values for string and bytes is a desired behaviour? It is at least very error prone. It should be interesting to have at least a note on README about this. For example, because of this I indexed a 35 TB data structure (file system based) incorrectly and I had to reindex everything again (3 days process to complete). Anyway, it's working as desired in my codebase here now as I understand the issue. Thanks a lot for the support!

**Comment by flier** [comment]
In Python, `str` and `unicode` is totally different type, so, the hash value is definitely difference. Please check [the discussion](https://stackoverflow.com/questions/18034272/python-str-vs-unicode-types/18034409) for more details :)

Sorry about the wasted time, I will update the README soon, thanks.
