### ISSUE TITLE
Installing pyhash==0.9.2 fails if LANG=C

### ISSUE THREAD

**Issue by itniemin** [flier/pyfasthash#32]
`setup.py` takes the "long description" from `README.md`. In 0.9.2 `README.md` includes non-ASCII characters, which causes `pip install` to fail in some locales. The problem seems to be quotes in the line: 

`/usr/lib/gcc/x86_64-linux-gnu/6/include/smmintrin.h:846:1: error: inlining failed in call to always_inline ‘long long unsigned int _mm_crc32_u64(long long unsigned int, long long unsigned int)’: target specific option mismatch`

Error message below:

```
$ LANG=C pip install pyhash-0.9.2.tar.gz 
--
Processing ./pyhash-0.9.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-p9vd98zb/setup.py", line 13, in <module>
        long_description = f.read()
      File "/home/itniemin/.virtualenvs/temp/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1874: ordinal not in range(128)
```

**Comment by flier** [comment]
It should be fixed in 0.9.3, thanks
